---
# tasks file for nginx
- name: install nginx
  yum: 
    name: nginx
    state: latest
  become_method: sudo
  become: True

- name: start nginx
  systemd:
    name: nginx
    state: started
  become_method: sudo
  become: True

- name: copy config
  template:
    src: nginx.j2
    dest: /etc/nginx/nginx.conf
  become_method: sudo
  become: True
  notify:
    - restart_nginx



