---
# vars file for tomcat
tomcat_v:
  7.0.82: 'ftp://ftp.byfly.by/pub/apache.org/tomcat/tomcat-7/v7.0.82/bin/apache-tomcat-7.0.82.tar.gz'
  8.0.47: 'ftp://ftp.byfly.by/pub/apache.org/tomcat/tomcat-8/v8.0.47/bin/apache-tomcat-8.0.47.tar.gz'
  8.0.48: 'ftp://ftp.byfly.by/pub/apache.org/tomcat/tomcat-8/v8.0.48/bin/apache-tomcat-8.0.48.tar.gz'
  8.5.24: 'ftp://ftp.byfly.by/pub/apache.org/tomcat/tomcat-8/v8.5.24/bin/apache-tomcat-8.5.24.tar.gz'
  9.0.2: 'ftp://ftp.byfly.by/pub/apache.org/tomcat/tomcat-9/v9.0.2/bin/apache-tomcat-9.0.2.tar.gz'
tomcat_link: "{{ tomcat_v[tomcat_version] }}"
tomcat_version: 8.0.48