---
# tasks file for tomcat_test

# Checks
- name: wait fot tomcat
  wait_for:
    host: master
    port: 8080
#    delay: 20  

- name: check tomcat 1
  shell: "curl master:8080 -I"
  register: check1
  failed_when: "'200' not in check1.stdout"
  changed_when: False    

- name: check tomcat 2
  shell: "systemctl status tomcat"
  register: check2
  changed_when: False

- name: check tomcat 3
  shell: "ps -ef | grep tomcat"
  register: check3
  failed_when: "'catalina' not in check3.stdout"
  changed_when: False

- name: Display check 1
  debug:
    msg: "Tomcat HTTP response code: {{ (check1.stdout.split(' '))[1] }}"

- name: Display check 2
  debug:
    msg: "Tomcat uptime: {{ (check2.stdout_lines[2].split(' '))[-2] }}"
