---
- hosts: master1
  vars:
    tomcat_version: 8.5.24
    tomcat_user: tomcat_as
    tomcat_group: tomcat_as_group
    catalina_home: "/opt/tomcat/{{ tomcat_version }}"
    java_version: java-1.8.0-openjdk.x86_64

  tasks:
  - name: install java
    yum:
      name: "{{ java_version }}"
    become_method: sudo
    become: True

  - name: make group for tomcat
    group:
      name: "{{ tomcat_group }}"
      state: present
    become_method: sudo
    become: True

  - name: make user for tomcat
    user:
      name: "{{ tomcat_user }}"
      group: "{{ tomcat_group }}"
    become_method: sudo
    become: True

  - name: mkdir for tomcat
    file:
      path: /opt/tomcat
      recurse: yes
      state: directory
    become_method: sudo
    become: True

  - name: check for existance 8.5.24
    stat:
      path: "{{ catalina_home }}"
    register: check

  - name: download tomcat
    get_url:
      url: ftp://ftp.byfly.by/pub/apache.org/tomcat/tomcat-8/v8.5.24/bin/apache-tomcat-8.5.24.tar.gz
      dest: /opt/tomcat/
    become_method: sudo
    become: True
    when: check.stat.exists == False

  - name: unarchive
    unarchive:
      src: /opt/tomcat/apache-tomcat-8.5.24.tar.gz
      dest: /opt/tomcat
      remote_src: yes
    become_method: sudo
    become: True
    when: check.stat.exists == False

  - name: rename folder
    command: "mv /opt/tomcat/apache-tomcat-8.5.24 {{ catalina_home }}"
    become_method: sudo
    become: True
    when: check.stat.exists == False

  - name: change owner for tomcat
    file:
      path: "{{ catalina_home }}"
      state: directory
      recurse: yes
      owner: "{{ tomcat_user }}"
      group: "{{ tomcat_group }}"
    become_method: sudo
    become: True

  - name: check for existance dir for logs
    stat:
      path: /var/log/tomcat/logs
    register: check_logs

  - name: mk dir for tomcat logs
    file:
      path: /var/log/tomcat/logs
      state: directory
      owner: "{{ tomcat_user }}"
      group: "{{ tomcat_group }}"
      mode: 0755
      recurse: yes
    become_method: sudo
    become: True
    when: check_logs.stat.exists == False

  - name: mk symlink for tomcat logs
    file:
      dest: /opt/tomcat/8.5.24/logs
      src: /var/log/tomcat/logs
      state: link
      owner: "{{ tomcat_user }}"
      group: "{{ tomcat_group }}"
      mode: 0755
      force: yes
    become_method: sudo
    become: True
 
  - name: copy service file
    copy:
      src: tomcat.service
      dest: /etc/systemd/system
    become_method: sudo
    become: True

  - name: enable service
    service:
      name: tomcat
      enabled: yes
      state: started
    become_method: sudo
    become: True


# Checks
  - name: wait fot tomcat
    wait_for:
      host: master
      port: 8080
      delay: 20  

  - name: check tomcat 1
    shell: "curl master:8080 -I"
    register: check1
    failed_when: "'200' not in check1.stdout"
    changed_when: False    

  - name: check tomcat 2
    shell: "systemctl status tomcat"
    register: check2
    changed_when: False

  - name: check tomcat 3
    shell: "ps -ef | grep tomcat"
    register: check3
    failed_when: "'catalina' not in check3.stdout"
    changed_when: False

  - name: Display check 1
    debug:
      msg: "Tomcat HTTP response code: {{ (check1.stdout.split(' '))[1] }}"
   
  - name: Display check 2
    debug:
      msg: "Tomcat uptime: {{ (check2.stdout_lines[2].split(' '))[-2] }}"
      
